name: Filiapolis
favicon: null
layout_spectrum: 0.32489
typography_spectrum: 0.57247
title: 'FILIAPOLIS: practical philosophy'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-50765416-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffb76a'
    - '#f57c00'
    - '#ffe4bd'
    - '#ffcd93'
    - '#f99e4c'
  brandStrength: 0.75
  lightness: 0.6385905467905104
  saturation: 0.8442276893183589
  rhythmicContrast: 0.6653326712548733
purpose: []
